version: 1.0.0.{build}.{branch}

image: Visual Studio 2017

nuget:
  account_feed: false
  
init:
 - git config --global core.autocrlf true

cache:
  - '%APPDATA%\npm-cache'    # npm cache
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 
before_build:
 - cmd: dotnet restore IdentityServer
 - cmd: npm install -g bower

build_script:
 - cmd: dotnet publish IdentityServer\src\HtBox.IdentityServer\project.json --output c:\Published
 - cmd: dotnet build IdentityServer\tests\HtBox.IdentityServer.Tests\project.json

test_script:
 - ps: cd .\IdentityServer\tests\HtBox.IdentityServer.Tests
 - cmd: dotnet test